# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: oldrel
    env:
      # Don't use 'vdiffr' on old R release
      VDIFFR_RUN_TESTS=false
      # Force checking without installed 'Suggested' pakcages.
      _R_CHECK_DEPENDS_ONLY_=true
  - r: release
    env:
      _R_CHECK_DEPENDS_ONLY_=true
  - r: devel
    env:
      # Temporarily don't use 'vdiffr' on R-devel until R-release becomes 4.1.0
      # This is because of some breaking change after 4.0.0 which changes some
      # lines in .svg test figures without any visual change.
      # TODO: start again using 'vdiffr' tests after R-release becomes 4.1.0
      VDIFFR_RUN_TESTS=false
      _R_CHECK_DEPENDS_ONLY_=true

branches:
  only:
  - master

after_success:
  - echo 'covr::codecov()' | R --vanilla
