# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: oldrel
    # Don't use 'vdiffr' on old R release
    env: VDIFFR_RUN_TESTS=false
  - r: release
  - r: devel
    # Temporarily don't use 'vdiffr' on R-devel until R-release becomes 4.1.0
    # This is because of some breaking change after 4.0.0 which changes some
    # lines in .svg test figures without any visual change.
    # TODO: start again using 'vdiffr' tests after R-release becomes 4.1.0
    env: VDIFFR_RUN_TESTS=false

branches:
  only:
  - master

after_success:
  - echo 'covr::codecov()' | R --vanilla
