# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: oldrel
    # Don't use vdiffr on old R release
    env: VDIFFR_RUN_TESTS=false
  - r: release
  - r: devel

branches:
  only:
  - master

after_success:
  - echo 'covr::codecov()' | R --vanilla
